name: Batch LaVitrine Pipeline

on:
  workflow_dispatch:
  schedule:
    - cron: '0 2 * * *'  # Runs daily at 1 AM UTC, which is 9 PM EST

jobs:
  placedesarts-com:
    uses: ./.github/workflows/pipeline.yml
    with:
      graph_url: 'http://kg.artsdata.ca/culture-creates/footlight/placedesarts-com'
      artifact: 'placedesarts-com'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
  dia-logGraphs:
    needs: placedesarts-com
    if: always() # This ensures the job runs regardless if the previous job failed
    uses: ./.github/workflows/pipeline.yml
    with:
      graph_url: 'http://kg.artsdata.ca/resource/dia-logGraphs'
      artifact: 'dia-logGraphs'  
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
  hector-charland:
    needs: dia-logGraphs
    if: always()
    uses: ./.github/workflows/pipeline.yml
    with:
      graph_url: 'http://kg.artsdata.ca/culture-creates/footlight/hector-charland-com'
      artifact: 'hector-charland-com'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
  theatredumarais-com:
    needs: hector-charland
    if: always()
    uses: ./.github/workflows/pipeline.yml
    with:
      graph_url: 'http://kg.artsdata.ca/culture-creates/footlight/theatredumarais-com'
      artifact: 'theatredumarais-com'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
  tout-culture:
    needs: theatredumarais-com
    uses: ./.github/workflows/pipeline.yml
    if: always()
    with:
      graph_url: 'http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/tout-culture'
      artifact: 'tout-culture-cms-events'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
  signe-laval:
    needs: tout-culture
    if: always()
    uses: ./.github/workflows/pipeline.yml
    with:
      graph_url: 'http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/signe-laval'
      artifact: 'signe-laval-cms-events'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
  culture-mauricie:
    needs: signe-laval
    if: always()
    uses: ./.github/workflows/pipeline.yml
    with:
      graph_url: 'http://kg.artsdata.ca/culture-creates/artsdata-planet-footlight/culture-mauricie'
      artifact: 'culture-mauricie-cms-events'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
  grandtheatre-qc-ca:
    needs: culture-mauricie
    if: always()
    uses: ./.github/workflows/pipeline.yml
    with:
      graph_url: 'http://kg.artsdata.ca/culture-creates/huginn/derived-grandtheatre-qc-ca'
      artifact: 'grandtheatre-qc-ca'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
