name: Batch LaVitrine Pipeline

on:
  workflow_dispatch:
    inputs:
      graph_url:
        description: 'Graph URL'
        type: string
        required: true
        default: 'http://kg.artsdata.ca/culture-creates/huginn/derived-grandtheatre-qc-ca'
      artifact:
        description: 'Artifact'
        type: string
        required: true
        default: 'grandtheatre-qc-ca'
    
jobs:
  call-pipeline:
    uses: ./.github/workflows/pipeline.yml
    with:
      graph_url: ${{ inputs.graph_url}}
      artifact: ${{ inputs.graph_url}}
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      PUBLISHER: ${{ secrets.PUBLISHER_URI_GREGORY }}
  