name: Pipeline for LaVitrine

on:
  workflow_dispatch:
    inputs:
      graph_url:
        description: 'Graph URL'
        type: string
        required: true
        default: 'http://kg.artsdata.ca/culture-creates/huginn/derived-grandtheatre-qc-ca'
      artifact:
        description: 'Artifact'
        type: string
        required: true
        default: 'derived-grandtheatre-qc-ca'
  workflow_call:
    inputs:
      graph_url:
        description: 'Graph URL'
        type: string
        required: true
      artifact:
        description: 'Artifact'
        type: string
        required: true
        
jobs:
  fetch-transform-data:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
        ruby-version: 3.1

    - name: Run Main Script
      run: |
          mkdir output ; cd src ; bundle exec ruby lavitrine_pipeline.rb ${{ inputs.graph_url }}

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact }}
        path: |
          ./output/raw-${{ inputs.artifact }}.json
          ./output/${{ inputs.artifact }}.json
          ./output/${{ inputs.artifact }}.yml
          ./output/${{ inputs.artifact }}-missing-artsdata-ids.txt
        retention-days: 1
      
  upload-to-s3:
    needs: fetch-transform-data
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.S3_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET_ACCESS_KEY }}
      AWS_REGION: ca-central-1 
      WEBHOSTING_BUCKET_NAME: huginn-data
    runs-on: ubuntu-latest
    steps:
    - name: Set current date as version
      id: set-version  # this is used on variable path
      run: |
        echo "version=$(date +'%Y-%m-%dT%H-%M-%S')" >> $GITHUB_OUTPUT
    - name: Get artifacts
      uses: actions/download-artifact@v2
      with:
        name: ${{ inputs.artifact }}
        path: ./output
    - name: Upload to S3
      run:  |
        aws s3 cp ./output/ s3://${{ env.WEBHOSTING_BUCKET_NAME }}/lavitrine/${{ steps.set-version.outputs.version }}/ --acl public-read --recursive
    - name: Set downloadUrl
      run: |
        echo "downloadUrl=https://${{ env.WEBHOSTING_BUCKET_NAME }}.s3.${{ env.AWS_REGION }}.amazonaws.com/lavitrine/${{ steps.set-version.outputs.version }}/${{ github.event.inputs.artifact }}.json" >> $GITHUB_OUTPUT

  register-on-artsdata-databus:
    runs-on: ubuntu-latest
    needs: upload-to-s3
    steps:
      - name: Register dump on Artsdata Databus
        run: |
          curl \
          -H 'Content-Type: application/json' \
          -X POST http://api.artsdata.ca/databus/  \
          --data '{ "artifact": "derived-grandtheatre-qc-ca",
                    "comment": "Dump of ${{ github.event.inputs.artifact }} using Github workflows",
                    "publisher": "${{ secrets.PUBLISHER_URI_GREGORY }}",
                    "group": "${{ github.event.repository.name }}",
                    "version": "${{ needs.upload-to-s3.outputs.version }}",
                    "downloadUrl": "${{ needs.upload-to-s3.outputs.downloadUrl }}",
                    "downloadFile": "${{ github.event.inputs.artifact }}.json",
                    "register_only": "true"
                  }'   